version: '3.8'

services:
  app:
    container_name: coinflip_service
    build:
      context: .
    command: >
      sh -c "
      echo coinflip_service is ready to fly!!;
      yarn start:dev
      "
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html/src
      - ./test:/var/www/html/test
    networks:
      - public

networks:
  public:
    external:
      name: public
