export const DB_CONNECTION_TOKEN = 'DB_CONNECTION_TOKEN';
export const PROCESSED_EVENTS_BLOCK_REPOSITORY = 'PROCESSED_EVENTS_BLOCK_REPOSITORY';
export const SETTINGS_REPOSITORY = 'SETTINGS_REPOSITORY';
export const CRYPTO_ERC_20_TOKEN_REPOSITORY = 'CRYPTO_ERC_20_TOKEN_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_BALANCE_REPOSITORY = 'USER_BALANCE_REPOSITORY';
